### ISSUE TITLE
Difficulties loading adversarially trained models

### ISSUE THREAD

**Issue by lukasShuber** [bethgelab/model-vs-human#13] opened 2021-11-29 12:39 UTC
I didn't succeed in loading the adversarially trained models. run_evaluation results in the following error: 

`HTTP Error 403: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`

Any idea how to fix this?

**Comment by rgeirhos** [comment] 2021-12-13 11:18
Thanks for pointing this out. This was caused by the external repository from which we obtained the adversarially trained models, and observed/fixed in https://github.com/microsoft/robust-models-transfer/issues/12 on their end. I updated the model URLs in commit [4131742](https://github.com/bethgelab/model-vs-human/commit/4131742176859d76e647e0764c29869b41dae3b7) which resolves the issue.

**Closed by rgeirhos** 2021-12-13 11:18 UTC
